from django.db import models

class Vendors(models.Model):
    vendorid = models.CharField(db_column='VENDORID', blank=False, null=False, max_length=50)
    remit = models.FloatField(db_column='REMIT', blank=True, null=True)
    filetype = models.FloatField(db_column='FILETYPE', blank=True, null=True)
    audtdate = models.CharField(db_column='AUDTDATE',max_length=50, blank=True, null=True)
    audttime = models.CharField(db_column='AUDTTIME',max_length=50, blank=True, null=True)
    audtuser = models.CharField(max_length=50, db_column='AUDTUSER', blank=True, null=True)
    audtorg = models.CharField(max_length=50, db_column='AUDTORG', blank=True, null=True)
    bankname = models.CharField(max_length=50, db_column='BANKNAME', blank=True, null=True)
    bsbno = models.IntegerField(db_column='BSBNO', blank=True, null=True)
    accno = models.IntegerField(db_column='ACCNO', blank=True, null=True)
    accname = models.CharField(max_length=50, db_column='ACCNAME', blank=True, null=True)
    payref = models.FloatField(db_column='PAYREF', blank=True, null=True)
    delmethod = models.IntegerField(db_column='DELMETHOD', blank=True, null=True)
    status = models.IntegerField(db_column='STATUS', blank=True, null=True)
    extra1 = models.FloatField(db_column='EXTRA1', blank=True, null=True)
    extra2 = models.FloatField(db_column='EXTRA2', blank=True, null=True)
    extra3 = models.FloatField(db_column='EXTRA3', blank=True, null=True)
    extra4 = models.FloatField(db_column='EXTRA4', blank=True, null=True)
    extra5 = models.FloatField(db_column='EXTRA5', blank=True, null=True)
    extra6 = models.FloatField(db_column='EXTRA6', blank=True, null=True)
    extra7 = models.FloatField(db_column='EXTRA7', blank=True, null=True)
    extra8 = models.FloatField(db_column='EXTRA8', blank=True, null=True)
    extra9 = models.FloatField(db_column='EXTRA9', blank=True, null=True)
    extra10 = models.FloatField(db_column='EXTRA10', blank=True, null=True)
    extra11 = models.FloatField(db_column='EXTRA11', blank=True, null=True)
    extra12 = models.FloatField(db_column='EXTRA12', blank=True, null=True)
    extra13 = models.FloatField(db_column='EXTRA13', blank=True, null=True)
    extra14 = models.FloatField(db_column='EXTRA14', blank=True, null=True)
    extra15 = models.FloatField(db_column='EXTRA15', blank=True, null=True)
    extra16 = models.FloatField(db_column='EXTRA16', blank=True, null=True)
    extra17 = models.FloatField(db_column='EXTRA17', blank=True, null=True)
    extra18 = models.FloatField(db_column='EXTRA18', blank=True, null=True)
    extra19 = models.FloatField(db_column='EXTRA19', blank=True, null=True)
    extra20 = models.FloatField(db_column='EXTRA20', blank=True, null=True)
    extra21 = models.FloatField(db_column='EXTRA21', blank=True, null=True)
    extra22 = models.FloatField(db_column='EXTRA22', blank=True, null=True)
    extra23 = models.FloatField(db_column='EXTRA23', blank=True, null=True)
    extra24 = models.FloatField(db_column='EXTRA24', blank=True, null=True)
    extra25 = models.FloatField(db_column='EXTRA25', blank=True, null=True)
    extra26 = models.FloatField(db_column='EXTRA26', blank=True, null=True)
    extra27 = models.FloatField(db_column='EXTRA27', blank=True, null=True)
    extra28 = models.FloatField(db_column='EXTRA28', blank=True, null=True)
    extra29 = models.FloatField(db_column='EXTRA29', blank=True, null=True)
    extra30 = models.FloatField(db_column='EXTRA30', blank=True, null=True)
    extra31 = models.FloatField(db_column='EXTRA31', blank=True, null=True)
    extra32 = models.FloatField(db_column='EXTRA32', blank=True, null=True)
    extra33 = models.FloatField(db_column='EXTRA33', blank=True, null=True)
    extra34 = models.FloatField(db_column='EXTRA34', blank=True, null=True)
    extra35 = models.FloatField(db_column='EXTRA35', blank=True, null=True)
    extra36 = models.FloatField(db_column='EXTRA36', blank=True, null=True)
    extra37 = models.FloatField(db_column='EXTRA37', blank=True, null=True)
    extra38 = models.FloatField(db_column='EXTRA38', blank=True, null=True)
    extra39 = models.FloatField(db_column='EXTRA39', blank=True, null=True)
    extra40 = models.FloatField(db_column='EXTRA40', blank=True, null=True)
    extra41 = models.FloatField(db_column='EXTRA41', blank=True, null=True)
    extra42 = models.FloatField(db_column='EXTRA42', blank=True, null=True)
    extra43 = models.FloatField(db_column='EXTRA43', blank=True, null=True)
    extra44 = models.FloatField(db_column='EXTRA44', blank=True, null=True)
    extra45 = models.FloatField(db_column='EXTRA45', blank=True, null=True)
    extra46 = models.FloatField(db_column='EXTRA46', blank=True, null=True)
    extra47 = models.FloatField(db_column='EXTRA47', blank=True, null=True)
    extra48 = models.FloatField(db_column='EXTRA48', blank=True, null=True)
    extra49 = models.FloatField(db_column='EXTRA49', blank=True, null=True)
    extra50 = models.FloatField(db_column='EXTRA50', blank=True, null=True)
    emailto = models.EmailField(db_column='EMAILTO', blank=True, null=True)
    edelmethod = models.IntegerField(db_column='EDELMETHOD', blank=True, null=True)
    xbsbno = models.CharField(max_length=50, db_column='XBSBNO', blank=True, null=True)
    xaccno = models.CharField(max_length=50, db_column='XACCNO', blank=True, null=True)
    rmtpasswd = models.IntegerField(db_column='RMTPASSWD', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'vendors_vendor'

    def __str__(self):
        return self.idvend

class Transactions(models.Model):
    idbank = models.CharField(db_column='IDBANK', max_length=50, blank=False, null=False)
    idvend = models.CharField(db_column='IDVEND',max_length=50, blank=False, null=False)
    idrmit = models.FloatField(db_column='IDRMIT', blank=True, null=True)
    longserial = models.IntegerField(db_column='LONGSERIAL', blank=True, null=True)
    datermit = models.CharField(max_length=50, db_column='DATERMIT', blank=True, null=True)
    audtdate = models.CharField(max_length=50, db_column='AUDTDATE', blank=True, null=True)
    audttime = models.DateTimeField(db_column='AUDTTIME', blank=True, null=True)
    audtuser = models.CharField(max_length=50, db_column='AUDTUSER', blank=True, null=True)
    audtorg = models.CharField(max_length=50, db_column='AUDTORG', blank=True, null=True)
    datebatch = models.CharField(max_length=50, db_column='DATEBATCH', blank=True, null=True)
    amtrmittc = models.FloatField(db_column='AMTRMITTC', blank=True, null=True)
    amtpaym = models.FloatField(db_column='AMTPAYM', blank=True, null=True)
    amtdisc = models.FloatField(db_column='AMTDISC', blank=True, null=True)
    paymcode = models.CharField(max_length=50, db_column='PAYMCODE', blank=True, null=True)
    codecurn = models.CharField(max_length=50, db_column='CODECURN', blank=True, null=True)
    idratetype = models.CharField(max_length=50, db_column='IDRATETYPE', blank=True, null=True)
    rateexchhc = models.FloatField(db_column='RATEEXCHHC', blank=True, null=True)
    swovrdrate = models.IntegerField(db_column='SWOVRDRATE', blank=True, null=True)
    textretrn = models.CharField(max_length=50, db_column='TEXTRETRN', blank=True, null=True)
    amtrounder = models.FloatField(db_column='AMTROUNDER', blank=True, null=True)
    daterate = models.IntegerField(db_column='DATERATE', blank=True, null=True)
    cntfiscyr = models.IntegerField(db_column='CNTFISCYR', blank=True, null=True)
    cntfiscper = models.IntegerField(db_column='CNTFISCPER', blank=True, null=True)
    textpayor = models.TextField(db_column='TEXTPAYOR', blank=True, null=True)
    cntbtch = models.IntegerField(db_column='CNTBTCH', blank=True, null=True)
    cntitem = models.IntegerField(db_column='CNTITEM', blank=True, null=True)
    swchkclrd = models.IntegerField(db_column='SWCHKCLRD', blank=True, null=True)
    amtrmithc = models.FloatField(db_column='AMTRMITHC', blank=True, null=True)
    amtadj = models.FloatField(db_column='AMTADJ', blank=True, null=True)
    dateclrd = models.IntegerField(db_column='DATECLRD', blank=True, null=True)
    datervrsd = models.IntegerField(db_column='DATERVRSD', blank=True, null=True)
    trxtypetxt = models.IntegerField(db_column='TRXTYPETXT', blank=True, null=True)
    idinvc = models.TextField(db_column='IDINVC', blank=True, null=True)
    rateop = models.IntegerField(db_column='RATEOP', blank=True, null=True)
    paymtype = models.IntegerField(db_column='PAYMTYPE', blank=True, null=True)
    cuid = models.IntegerField(db_column='CUID', blank=True, null=True)
    drillapp = models.TextField(db_column='DRILLAPP', blank=True, null=True)
    drilltype = models.IntegerField(db_column='DRILLTYPE', blank=True, null=True)
    drilldwnlk = models.IntegerField(db_column='DRILLDWNLK', blank=True, null=True)
    idacct = models.FloatField(db_column='IDACCT', blank=True, null=True)
    swnonrcvbl = models.IntegerField(db_column='SWNONRCVBL', blank=True, null=True)
    swjob = models.IntegerField(db_column='SWJOB', blank=True, null=True)
    idinvcmtch = models.FloatField(db_column='IDINVCMTCH', blank=True, null=True)
    swtxamtctl = models.IntegerField(db_column='SWTXAMTCTL', blank=True, null=True)
    swtxbsectl = models.IntegerField(db_column='SWTXBSECTL', blank=True, null=True)
    codetaxgrp = models.FloatField(db_column='CODETAXGRP', blank=True, null=True)
    codetax1 = models.FloatField(db_column='CODETAX1', blank=True, null=True)
    codetax2 = models.FloatField(db_column='CODETAX2', blank=True, null=True)
    codetax3 = models.FloatField(db_column='CODETAX3', blank=True, null=True)
    codetax4 = models.FloatField(db_column='CODETAX4', blank=True, null=True)
    codetax5 = models.FloatField(db_column='CODETAX5', blank=True, null=True)
    taxclass1 = models.IntegerField(db_column='TAXCLASS1', blank=True, null=True)
    taxclass2 = models.IntegerField(db_column='TAXCLASS2', blank=True, null=True)
    taxclass3 = models.IntegerField(db_column='TAXCLASS3', blank=True, null=True)
    taxclass4 = models.IntegerField(db_column='TAXCLASS4', blank=True, null=True)
    taxclass5 = models.IntegerField(db_column='TAXCLASS5', blank=True, null=True)
    txbse1tc = models.FloatField(db_column='TXBSE1TC', blank=True, null=True)
    txbse2tc = models.FloatField(db_column='TXBSE2TC', blank=True, null=True)
    txbse3tc = models.FloatField(db_column='TXBSE3TC', blank=True, null=True)
    txbse4tc = models.FloatField(db_column='TXBSE4TC', blank=True, null=True)
    txbse5tc = models.FloatField(db_column='TXBSE5TC', blank=True, null=True)
    txamt1tc = models.FloatField(db_column='TXAMT1TC', blank=True, null=True)
    txamt2tc = models.FloatField(db_column='TXAMT2TC', blank=True, null=True)
    txamt3tc = models.FloatField(db_column='TXAMT3TC', blank=True, null=True)
    txamt4tc = models.FloatField(db_column='TXAMT4TC', blank=True, null=True)
    txamt5tc = models.FloatField(db_column='TXAMT5TC', blank=True, null=True)
    txtottc = models.FloatField(db_column='TXTOTTC', blank=True, null=True)
    amtnettc = models.FloatField(db_column='AMTNETTC', blank=True, null=True)
    txalltc = models.FloatField(db_column='TXALLTC', blank=True, null=True)
    txexptc = models.FloatField(db_column='TXEXPTC', blank=True, null=True)
    txrectc = models.FloatField(db_column='TXRECTC', blank=True, null=True)
    codecurnrc = models.FloatField(db_column='CODECURNRC', blank=True, null=True)
    swtxctlrc = models.IntegerField(db_column='SWTXCTLRC', blank=True, null=True)
    raterc = models.FloatField(db_column='RATERC', blank=True, null=True)
    ratetyperc = models.FloatField(db_column='RATETYPERC', blank=True, null=True)
    ratedaterc = models.IntegerField(db_column='RATEDATERC', blank=True, null=True)
    rateoprc = models.IntegerField(db_column='RATEOPRC', blank=True, null=True)
    txamt1rc = models.FloatField(db_column='TXAMT1RC', blank=True, null=True)
    txamt2rc = models.FloatField(db_column='TXAMT2RC', blank=True, null=True)
    txamt3rc = models.FloatField(db_column='TXAMT3RC', blank=True, null=True)
    txamt4rc = models.FloatField(db_column='TXAMT4RC', blank=True, null=True)
    txamt5rc = models.FloatField(db_column='TXAMT5RC', blank=True, null=True)
    txtotrc = models.FloatField(db_column='TXTOTRC', blank=True, null=True)
    txallrc = models.FloatField(db_column='TXALLRC', blank=True, null=True)
    txexprc = models.FloatField(db_column='TXEXPRC', blank=True, null=True)
    txrecrc = models.FloatField(db_column='TXRECRC', blank=True, null=True)
    txbse1hc = models.FloatField(db_column='TXBSE1HC', blank=True, null=True)
    txbse2hc = models.FloatField(db_column='TXBSE2HC', blank=True, null=True)
    txbse3hc = models.FloatField(db_column='TXBSE3HC', blank=True, null=True)
    txbse4hc = models.FloatField(db_column='TXBSE4HC', blank=True, null=True)
    txbse5hc = models.FloatField(db_column='TXBSE5HC', blank=True, null=True)
    txamt1hc = models.FloatField(db_column='TXAMT1HC', blank=True, null=True)
    txamt2hc = models.FloatField(db_column='TXAMT2HC', blank=True, null=True)
    txamt3hc = models.FloatField(db_column='TXAMT3HC', blank=True, null=True)
    txamt4hc = models.FloatField(db_column='TXAMT4HC', blank=True, null=True)
    txamt5hc = models.FloatField(db_column='TXAMT5HC', blank=True, null=True)
    txtothc = models.FloatField(db_column='TXTOTHC', blank=True, null=True)
    amtnethc = models.FloatField(db_column='AMTNETHC', blank=True, null=True)
    txallhc = models.FloatField(db_column='TXALLHC', blank=True, null=True)
    txexphc = models.FloatField(db_column='TXEXPHC', blank=True, null=True)
    txrechc = models.FloatField(db_column='TXRECHC', blank=True, null=True)
    cntacc = models.IntegerField(db_column='CNTACC', blank=True, null=True)
    amtacctc = models.FloatField(db_column='AMTACCTC', blank=True, null=True)
    amtacchc = models.FloatField(db_column='AMTACCHC', blank=True, null=True)
    datebus = models.IntegerField(db_column='DATEBUS', blank=True, null=True)
    amtwht1tc = models.FloatField(db_column='AMTWHT1TC', blank=True, null=True)
    amtwht2tc = models.FloatField(db_column='AMTWHT2TC', blank=True, null=True)
    amtwht3tc = models.FloatField(db_column='AMTWHT3TC', blank=True, null=True)
    amtwht4tc = models.FloatField(db_column='AMTWHT4TC', blank=True, null=True)
    amtwht5tc = models.FloatField(db_column='AMTWHT5TC', blank=True, null=True)
    amtcxbs1tc = models.FloatField(db_column='AMTCXBS1TC', blank=True, null=True)
    amtcxbs2tc = models.FloatField(db_column='AMTCXBS2TC', blank=True, null=True)
    amtcxbs3tc = models.FloatField(db_column='AMTCXBS3TC', blank=True, null=True)
    amtcxbs4tc = models.FloatField(db_column='AMTCXBS4TC', blank=True, null=True)
    amtcxbs5tc = models.FloatField(db_column='AMTCXBS5TC', blank=True, null=True)
    amtcxtx1tc = models.FloatField(db_column='AMTCXTX1TC', blank=True, null=True)
    amtcxtx2tc = models.FloatField(db_column='AMTCXTX2TC', blank=True, null=True)
    amtcxtx3tc = models.FloatField(db_column='AMTCXTX3TC', blank=True, null=True)
    amtcxtx4tc = models.FloatField(db_column='AMTCXTX4TC', blank=True, null=True)
    amtcxtx5tc = models.FloatField(db_column='AMTCXTX5TC', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'transactions_transaction'

    def __str__(self):
        return self.idvend